<?php
/**
 * Copyright © 2015 PlazaThemes.com. All rights reserved.

 * @author PlazaThemes Team <contact@plazathemes.com>
 */
if($this->getConfig('enable_frontend')):
	$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
	$image = 'category_page_grid';
	$_productHelper = $this->helper('Magento\Catalog\Helper\Product');
	$block = $this->getBlockProduct();
 
	$auto = $this->getConfig('auto');
	if($auto)
		$auto = 'true';
	else
		$auto = 'false';
	$default = $this->getConfig('default');
	$desktop = $this->getConfig('desktop');
	$desktop_small = $this->getConfig('desktop_small');
	$tablet = $this->getConfig('tablet');
	$mobile = $this->getConfig('mobile');
	$rows = $this->getConfig('rows');
	$show_next_back = $this->getConfig('show_next_back');
	$pagination = $this->getConfig('pagination');
	if($this->getConfig('speed'))
		$speed = $this->getConfig('speed');
	else
		$speed = '3000';
	if($show_next_back)
		$show_next_back = 'true';
	else
		$show_next_back = 'false';
	$show_navigation_control = $this->getConfig('show_navigation_control');
	if($show_navigation_control)
		$show_navigation_control = 'true';
	else
		$show_navigation_control = 'false';
?>
<div class="pt-recentproduct-container">
	<div class="title"><h2><?php echo $this->getConfig('title') ?></h2></div>
	<ul class="ptowl">
	<?php
	$i = 0;
	 foreach($this->getProducts() as $_product)
	{
	if($i%$rows == 0):
	?>
		<li class="product-item">
	<?php
	endif;
			$productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(400)->getUrl();
		?>
		
		<div class="product-item-inner">
			<a href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $productImage; ?>" alt=""/></a>
			<a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_product->getName() ?></a>
			<?php
				echo $block->getProductPrice($_product)
			?>
			<div class="product actions product-item-actions">
			<div class="actions-primary">
				<?php if ($_product->isSaleable()): ?>
					<?php $postParams = $block->getAddToCartPostParams($_product); ?>
					<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
						<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
						<input type="hidden" name="<?php /* @escapeNotVerified */ //echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ //echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
						<?php echo $block->getBlockHtml('formkey')?>
						<button type="submit"
								title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
								class="action tocart primary">
							<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
						</button>
					</form>
				<?php else: ?>
					<?php if ($_product->getIsSalable()): ?>
						<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
					<?php else: ?>
						<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
					<?php endif; ?>
				<?php endif; ?>
			</div>
			<div data-role="add-to-links" class="actions-secondary">
				<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
					<a href="#"
					   class="action towishlist"
					   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
					   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
					   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
					   data-action="add-to-wishlist"
					   role="button">
						<span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
					</a>
				<?php endif; ?>
				<?php
				$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
				?>
				<a href="#"
				   class="action tocompare"
				   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
				   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
				   role="button">
					<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
				</a>
			</div>
			</div>
		</div>
	<?php if($i%$rows == $rows - 1): ?>
		</li>
	<?php
	endif;
	$i++;
	}
	?>
	</ul>
</div>
<script type="text/javascript">
	require([
		"jquery"
	], function($){
		$(document).ready(function(){
			$(".pt-recentproduct-container .ptowl").owlCarousel({
				<?php
					if(($auto== 'true') && $speed):
				?>
				autoPlay : <?php echo $speed; ?>,
				<?php
					endif;
				?>
				items : <?php echo $default; ?>,
				itemsDesktop : [1199,<?php echo $desktop; ?>],
				itemsDesktopSmall : [980,<?php echo $desktop_small; ?>],
				itemsTablet: [768,<?php echo $tablet; ?>],
				itemsMobile : [479,<?php echo $mobile; ?>],
				slideSpeed : <?php echo $pagination; ?>,
				paginationSpeed : <?php echo $pagination; ?>,
				rewindSpeed : <?php echo $pagination; ?>,
				addClassActive: true,
				navigation : <?php echo $show_next_back; ?>,
				stopOnHover : true,
				pagination : <?php echo $show_navigation_control; ?>,
				scrollPerPage:true,
			});
		});
	});
</script>

<?php
endif;
?>