	<?php 
		$enable = $block->getConfig('enabled');
		if($enable < 1) return ; 
		$items = $block->getConfig('items');
		$speed = $block->getConfig('speed');
		$qty = $block->getConfig('qty');
		$showCart = $block->getConfig('addtocart');
		$showWishlist = $block->getConfig('wishlist');
		$showCompare = $block->getConfig('compare');
		$show_navigation = $block->getConfig('navigation');
		$show_pagination = $block->getConfig('pagination');
		$auto = $block->getConfig('auto');
		$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
		$image = 'new_products_content_widget_grid';
		$type = 'widget-new-grid';
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
		$rows = $block->getConfig('row');
	?>

	<ul class="tabs">
		<?php 
			$tab_contents = $block->getTabContent() ; 
	    $count=0;			
		foreach($tab_contents as $tab) {
			?>
		<li rel="tab_<?php echo $tab['id'];?>"  <?php if ($count==0) ?> class="active" > <?php echo $tab['name'];?></li>
			<?php
			$count ++; 
		}
		?>
	</ul>
	<div class="tab_container"> 
	   <?php 
		foreach($tab_contents as $tab) {
		?>
		 <div id="tab_<?php echo $tab['id'];?>" class="tab_content"> 
		 	<div class="productTabContent owl-carousel">
						<?php 
							$i=0;
							$productItems =  $tab['productInfo']; 
							foreach($productItems as $_item) { 
									$productImage = $block->getImage($_item, $image);
							?>
								<?php if($i++%$rows==0) { ?> <div class="product_row"> <?php } ?>
								<div class="item product-item-info">
									<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
										<?php echo $productImage->toHtml() ?>
									</a>
									<strong class="product-item-name">
										<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
										   href="<?php echo $block->getProductUrl($_item) ?>"
										   class="product-item-link">
											<?php echo $block->escapeHtml($_item->getName()) ?>
										</a>
									</strong>
									 <?php
										echo $block->getProductPrice($_item);
									 ?>
									 
									<?php if ($templateType): ?>
										<?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
									<?php endif; ?>
									<?php if ($showWishlist || $showCompare || $showCart): ?>
											<div class="product-item-actions">
												<?php if ($showCart): ?>
													<div class="actions-primary">
														<?php if ($_item->isSaleable()): ?>
															<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																<button class="action tocart primary"
																		data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getAddToCartUrl($_item) ?>"}}'
																		type="button" title="<?php echo __('Add to Cart') ?>">
																	<span><?php echo __('Add to Cart') ?></span>
																</button>
															<?php else: ?>
																<?php
																	$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																	$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																?>
																<button class="action tocart primary"
																		data-post='<?php echo $postData; ?>'
																		type="button" title="<?php echo __('Add to Cart') ?>">
																	<span><?php echo __('Add to Cart') ?></span>
																</button>
															<?php endif; ?>
														<?php else: ?>
															<?php if ($_item->getIsSalable()): ?>
																<div class="stock available"><span><?php echo __('In stock') ?></span></div>
															<?php else: ?>
																<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
															<?php endif; ?>
														<?php endif; ?>
													</div>
												<?php endif; ?>
												<?php if ($showWishlist || $showCompare): ?>
													<div class="actions-secondary" data-role="add-to-links">
														<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
															<a href="#"
															   data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
															   class="action towishlist" data-action="add-to-wishlist"
															   title="<?php echo __('Add to Wishlist') ?>">
																<span><?php echo __('Add to Wishlist') ?></span>
															</a>
														<?php endif; ?>
														<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
															<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
															<a href="#" class="action tocompare"
															   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
															   title="<?php echo __('Add to Compare') ?>">
																<span><?php echo __('Add to Compare') ?></span>
															</a>
														<?php endif; ?>
													</div>
												<?php endif; ?>
											</div>
										<?php endif; ?>
								</div>
								 <?php if($i%$rows==0 || $i == count($productItems)) { ?> </div> <?php }?>
							<?php 
							}
							?>
				
		
		 

					</div>
		 </div>
		
		<?php 
		} 
		?>
	</div>

	
<script type="text/javascript">
require(["jquery", "owlcarousel/js"], function($){

	$(".tab_content").hide();
	$(".tab_content:first").show(); 

	$("ul.tabs li").click(function() {
		$("ul.tabs li").removeClass("active");
		$(this).addClass("active");
		$(".tab_content").hide();
		$(".tab_content").removeClass("animate1");
		var activeTab = $(this).attr("rel"); 
		$("#"+activeTab) .addClass("animate1");
		$("#"+activeTab).fadeIn(); 
	});
	
	  $(".productTabContent").owlCarousel({
	    		items : <?php if($items) { echo $items; } else { echo 5; }?>,
				autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
				slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
				navigation : <?php if($show_navigation) echo 'true'; else echo 'false'; ?>,
				stopOnHover : true,
				pagination : <?php if($show_pagination) echo 'true'; else echo 'false'; ?>,
				pagination : true,
				itemsDesktop : [1200,1],
				itemsDesktopSmall : [1000,1],
				itemsTablet: [680,2],
				itemsMobile : [460,1]
	});
	

});
 

</script> 


