<?php
/**
 * Copyright © 2015 PlazaThemes.com. All rights reserved.

 * @author PlazaThemes Team <contact@plazathemes.com>
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Plazathemes\Blog\Block\Post\View\RelatedProducts
 */
?>

<?php
if ($exist = $block->getItems()->getSize() && $this->displayProducts()) {
    $type = 'related';
    $class = $type;

    $image = 'related_products_list';
    $title = __('Related Products');
    $items = $block->getItems();
    $limit = 0;
    $shuffle = 0;
    $canItemsAddToCart = true;

    $showWishlist = true;
    $showCompare = true;
    $showCart = false;
    $templateType = null;
    $description = false;
}
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
        <?php else: ?>
            <div class="block <?php echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php echo $class; ?>">
    <?php endif; ?>
    <div class="block-title group-title1 title">
        <h2><strong id="block-<?php echo $class?>-heading" role="heading" aria-level="2"><?php echo $title; ?></strong></h2>
    </div>
    <div class="block-related-post block-content content" aria-labelledby="block-<?php echo $class?>-heading">
	<div class="owl-container">
        <div class="products wrapper grid products-grid products-<?php echo $type; ?>">
            <div class="products list items product-items">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($type == 'related' || $type == 'upsell'): ?>
                    <?php echo($iterator++ == 1) ? '<div class="item product product-item" style="display: none;">' : '</div><div class="item product product-item" style="display: none;">' ?>
                <?php else: ?>
                    <?php echo($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
                <?php endif; ?>
                <div class="product-item-info <?php echo $available; ?> item-inner">
					<div class="image-container">
						<?php
							$newFromDate = $_item->getNewsFromDate();
							$newToDate = $_item->getNewsToDate();                
							$now = date("Y-m-d H:m:s");
							// Get the Special Price
							$specialprice = $_item->getSpecialPrice(); 
							// Get the Special Price FROM date
							$specialPriceFromDate = $_item->getSpecialFromDate();
							// Get the Special Price TO date
							$specialPriceToDate = $_item->getSpecialToDate();
							// Get Current date
						   if ($specialprice&&(($specialPriceFromDate <= $now && $specialPriceToDate >= $now) || (($specialPriceFromDate <= $now && $specialPriceFromDate != NULL) && $specialPriceToDate  == ''))){
							$_savePercent = 100 - round(($_item->getSpecialPrice() / $_item->getPrice())*100);
							echo "<span class='sale'>sale</span>";
						   }

						   if((($newFromDate <= $now && $newToDate >= $now) || (($newFromDate <= $now && $newFromDate != NULL) && $newToDate == NULL))) {
						   ?>
						   <span class="new"><?php echo __('new') ?></span>
						   <?php
						   } 
						?>
						<?php echo '<!-- ' . $image . '-->' ?>
						<a href="<?php echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
							<?php echo $block->getImage($_item, $image)->toHtml(); ?>
						</a>
							<div class="box-hover">

								<?php if ($showWishlist || $showCompare || $showCart): ?>
									<div class="product actions product-item-actions">
										<?php if ($showWishlist || $showCompare): ?>
											<div class="secondary-addto-links actions-secondary add-to-links" data-role="add-to-links">
												<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
													<a href="#" data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php echo __('Add to Wish List') ?>">
														<span><?php echo __('Add to Wish List') ?></span>
													</a>
												<?php endif; ?>
												<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
													<?php
													$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
													?>
													<a href="#" class="action tocompare"
													   data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
													   data-role="add-to-links"
													   title="<?php echo __('Add to Compare'); ?>">
														<span><?php echo __('Add to Compare') ?></span>
													</a>
												<?php endif; ?>
											</div>
										<?php endif; ?>
									</div>
								<?php endif; ?>
							</div>						
					</div>
                    <div class="product details product-item-details">
						<div class="box-info">
							<strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->getProductUrl($_item) ?>">
                            <?php echo $block->escapeHtml($_item->getName()) ?></a>
							</strong>
							<?php if ($templateType): ?>
								<?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
							<?php endif; ?>
							<div class="item-price">
								<?php echo $block->getProductPrice($_item); ?>
							</div>
									<div class="actions-primary">
										<?php if ($_item->isSaleable()): ?>
											<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
												<button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php  echo __('Add to Cart') ?>">
													<span><?php echo __('Add to Cart') ?></span>
												</button>
											<?php else: ?>
												<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
												$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
												?>
												<button class="action tocart primary"
														data-post='<?php echo $postData; ?>'
														type="button" title="<?php echo __('Add to Cart') ?>">
													<span><?php echo __('Add to Cart') ?></span>
												</button>
											<?php endif; ?>
										<?php else: ?>
											<?php if ($_item->getIsSalable()): ?>
												<div class="stock available"><span><?php echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
						</div>
                    </div>
                </div>
                    <?php echo($iterator == count($items)+1) ? '</div>' : '' ?>
                <?php endforeach ?>
            </div>
        </div>
		</div>
	</div>
</div>
<script type="text/javascript">
	require(["jquery","owlcarousel/minjs"], function($,owlCarousel){
		$(".products-related .product-items").owlCarousel({
			slideSpeed :     	1000,
			items :             3,
			itemsDesktop :      [1199,3],
			itemsDesktopSmall : [992,2],
			itemsTablet:        [767,1],
			itemsMobile :       [480,1],
			navigation :        true,
			stopOnHover :       true,
			pagination :       	false
		});
	});
</script>
<?php endif;?>