<div class="box-home">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-sm-6 col-sms-12">
				<div class="banner-slider">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('bannerslider.phtml')->toHtml();?> 
				</div>
			</div>
			<div class="col-md-6 col-sm-6 col-sms-12">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ma-banner2')->toHtml();?>
			</div>
		</div>
	</div>
</div>