<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter">
    <div class="title"><strong>Newsletter</strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="newsletter">SIGN UP FOR OUR NEWSLETTER & PROMOTIONS - PRESS THE BUTTON BELLOW !</label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>

                </div>
				<div class="actions">
					<button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Sign up') ?>" type="submit">
						<span><?php /* @escapeNotVerified */ echo __('Subscribe!') ?></span>
					</button>
				</div>				
            </div>
            
        </form>
    </div>
</div>
