<?php
/**
 * Copyright © 2016 PlazaThemes.com. All rights reserved.
 *
 * @author PlazaThemes Team <contact@plazathemes.com>
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Plazathemes\Layerednavigation\Block\Product\ProductList\Toolbar
 */
use Plazathemes\Layerednavigation\Block\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?php /* @escapeNotVerified */ echo __('Sort By') ?></label>
    <select id="sorter"
            <?php if($block->isEnabledAjaxLayered()): ?>
                data-filter="order"
            <?php endif; ?>
            data-role="sorter"
            class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <option value="<?php /* @escapeNotVerified */ echo $_key; ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?php echo $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a  title="<?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?>"
            href="javascript:void(0);"
            class="action sorter-action sort-desc"
            <?php if($block->isEnabledAjaxLayered()): ?>
                data-filter="dir"
            <?php endif; ?>
            data-role="direction-switcher"
            data-value="asc">
            <span><?php /* @escapeNotVerified */ echo __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a  title="<?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?>"
            href="javascript:void(0);"
            <?php if($block->isEnabledAjaxLayered()): ?>
                data-filter="dir"
            <?php endif; ?>
            class="action sorter-action sort-asc"
            data-role="direction-switcher"
            data-value="desc">
            <span><?php /* @escapeNotVerified */ echo __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
</div>
