<?php
/**
 * Copyright © 2016 PlazaThemes.com. All rights reserved.
 *
 * @author PlazaThemes Team <contact@plazathemes.com>
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Plazathemes\Layerednavigation\Block\Product\ProductList\Toolbar
 */
use Plazathemes\Layerednavigation\Block\Product\ProductList\Toolbar;
?>
<?php if ($block->isEnabledViewSwitcher()): ?>
<div class="modes">
    <?php $_modes = $block->getModes(); ?>
    <?php if ($_modes && count($_modes) > 1): ?>
    <strong class="modes-label" id="modes-label"><?php /* @escapeNotVerified */ echo __('View as') ?></strong>
    <?php foreach ($block->getModes() as $_code => $_label): ?>
        <?php if ($block->isModeActive($_code)): ?>
            <strong title="<?php /* @escapeNotVerified */ echo $_label ?>"
                class="modes-mode active mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                data-value="<?php /* @escapeNotVerified */ echo strtolower($_code); ?>">
                <span><?php /* @escapeNotVerified */ echo $_label ?></span>
            </strong>
        <?php else: ?>
            <a  class="modes-mode mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                title="<?php /* @escapeNotVerified */ echo $_label ?>"
                href="javascript:void(0);"
                <?php if($block->isEnabledAjaxLayered()): ?>
                    data-filter="mode"
                <?php endif; ?>
                data-role="mode-switcher"
                data-value="<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                id="mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>"
                aria-labelledby="modes-label mode-<?php /* @escapeNotVerified */ echo strtolower($_code); ?>">
                <span><?php /* @escapeNotVerified */ echo $_label ?></span>
            </a>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
<?php endif; ?>
