<?php
   /**
    * Copyright © 2015 Magento. All rights reserved.
    * See COPYING.txt for license details.
    */
   
   // @codingStandardsIgnoreFile
   
   /* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
   ?>
<?php
   switch ($type = $block->getType()) {
   
   
   
		case 'upsell':
			/** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
			if ($exist = count($block->getItemCollection()->getItems())) {
				$type = 'upsell';
				$class = $type;

				$image = 'upsell_products_list';
				$title = __('Upsell Products');
				$items = $block->getItemCollection()->getItems();
				$limit = $block->getItemLimit('upsell');
				$shuffle = 0;

				$showWishlist = true;
				$showCompare = true;
				$showCart = true;
				$templateType = null;
				$description = false;
				$canItemsAddToCart = false;
			}
			break;
   
       case 'other':
       break;
   }
   ?>
<?php if ($exist):?>
<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'upsell'): ?>
<section class="block <?php echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php else: ?>
<section class="block <?php echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php endif; ?>
<?php else: ?>
<section class="block <?php echo $class; ?>">
   <?php endif; ?>
   <header class="group-title1">
      <h2 id="block-<?php echo $class?>-heading" role="heading" aria-level="2"><?php echo $title; ?></h2>
   </header>
    
	<div class="block-content content" aria-labelledby="block-<?php echo $class?>-heading"> 
	   <div class="owl-container">
			<div id="upsell_product_slider" class="owl-carousel">
				<?php $iterator = 1; ?>
				<?php 
					$i = 0;
					$rows = 1;
				?>
				<?php foreach ($items as $_item): ?>
				<?php $available = ''; ?>  
				<?php
					$productImage = $block->getImage($_item, $image);
					
					
				?>
					<?php if ($i++%$rows==0) { ?>
					<div class="item">
					<?php } ?>
						<div class="item-inner">
							<div class="image-container">

								<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
									<?php echo $productImage->toHtml() ?>
								</a>
							</div>
							<div class="box-info">
								<strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->getProductUrl($_item) ?>">
									<?php echo $block->escapeHtml($_item->getName()) ?></a>
								</strong>
								<?php if ($templateType): ?>
								<?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
								<?php endif; ?>
								<div class="item-price">
									<?php echo $block->getProductPrice($_item); ?>
								</div>
							</div>
						</div>
					<?php if($i%$rows==0 || $i == count($items)) { ?> 
					</div> 
					<?php } ?>
				<?php endforeach ?>
			</div>
		</div> 
    </div> 
</section>
<?php endif;?>
<script type="text/javascript">
   require(["jquery","owlcarousel/minjs"], function($,owlCarousel){
   	
      $("#upsell_product_slider").owlCarousel({
   		items : 3,
		itemsDesktop : [1200,3],
   		itemsDesktopSmall : [992,3],
   		itemsTablet: [767,2],
   		itemsMobile : [480,1],
   		autoPlay : false,
   		slideSpeed : 3000,
   		navigation : true,
   		stopOnHover : true,
   		pagination : false,
      });
      
   });
</script>
